In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import numpy as np


uri = "https://raw.githubusercontent.com/lucianoMarchezan/dataSTest/main/data/graphs_avg.csv"
graphs = pd.read_csv(uri)

#filter = graphs["model_name"] == "Auction"
#graphs.where(filter,inplace = True)
graphs["repairs_applied_count"] = graphs["repairs_applied_count"].replace(0,np.nan)
byModel = graphs.groupby("model_name").std() 
byModel.loc[:, ~byModel.columns.isin(['idchange_prop', 'graph_number'])] # select all columns except these

,prop_time,repairs_prop,paths,consistent_states,dead_ends,abstract_states,repairs_applied_count,inconsistencies_fixed,conflict_detection_time,conflicts,repairs_filtered
model_name,,,,,,,,,,,
Auction,4.799359,1.290939,1.290939,0.596774,0.000000,0.766855,0.855585,0.000000,74.622641,3.435413,1.330767
Ball,123.383008,4.833908,4.833908,2.804758,0.000000,2.041241,NaN,0.000000,17.440375,15.513435,6.531973
DSpace,7000.167804,4.221573,4.172676,0.830733,0.000000,3.951816,0.275171,0.052522,717.350267,0.993113,0.426540
JCGrid,1066.321647,1.621209,1.621209,0.711631,0.000000,0.994949,0.497009,0.000000,393.595829,2.793278,0.740486
SPEM,4.498148,0.948683,0.948683,0.316228,0.000000,1.032796,0.000000,0.000000,0.316228,1.337494,0.849837
TIM,4.893640,1.533930,1.533930,0.766965,0.000000,0.766965,0.855585,0.000000,5.329962,1.349171,0.894792
TravelAgency,45.147536,83.857021,83.857021,2.236068,0.000000,81.621076,1.341641,0.000000,545.273143,1539.761605,84.636281
gcs,2588.087606,7802.291708,13444.939435,1739.976902,1116.879492,2116.224614,2.529822,2.427120,8306.450871,3799.669892,2890.029802
glide,90.165201,1.569874,1.569874,0.754117,0.000000,0.942689,0.503236,0.000000,1.094606,2.722152,0.808693
globus,428.247206,9.202661,9.087842,0.835894,0.000000,9.011708,0.501707,0.116554,25.683366,66.116997,3.054598
oodt,15661.076211,11.625995,11.486980,0.801221,0.030206,11.443209,0.449289,0.146417,469.098671,3.427594,0.954066

In [ ]:
byModel.loc[:, byModel.columns.isin(['model_name', 'repairs_prop', 'paths', 'consistent_states', 'abstract_states', 'dead_ends', 'repairs_applied_count'])] # select all these columns

,repairs_prop,paths,consistent_states,dead_ends,abstract_states,repairs_applied_count
model_name,,,,,,
Auction,1.290939,1.290939,0.596774,0.000000,0.766855,0.855585
Ball,4.833908,4.833908,2.804758,0.000000,2.041241,NaN
DSpace,4.221573,4.172676,0.830733,0.000000,3.951816,0.275171
JCGrid,1.621209,1.621209,0.711631,0.000000,0.994949,0.497009
SPEM,0.948683,0.948683,0.316228,0.000000,1.032796,0.000000
TIM,1.533930,1.533930,0.766965,0.000000,0.766965,0.855585
TravelAgency,83.857021,83.857021,2.236068,0.000000,81.621076,1.341641
gcs,7802.291708,13444.939435,1739.976902,1116.879492,2116.224614,2.529822
glide,1.569874,1.569874,0.754117,0.000000,0.942689,0.503236
globus,9.202661,9.087842,0.835894,0.000000,9.011708,0.501707
oodt,11.625995,11.486980,0.801221,0.030206,11.443209,0.449289

In [ ]:
byModel.loc[:, byModel.columns.isin(['prop_time', 'conflict_detection_time'])] # select all these columns

                 prop_time  conflict_detection_time
model_name
Auction           4.799359                74.622641
Ball            123.383008                17.440375
DSpace         7000.167804               717.350267
JCGrid         1066.321647               393.595829
SPEM              4.498148                 0.316228
TIM               4.893640                 5.329962
TravelAgency     45.147536               545.273143
gcs            2588.087606              8306.450871
glide            90.165201                 1.094606
globus          428.247206                25.683366
oodt          15661.076211               469.098671

In [ ]:
byModel.loc[:, byModel.columns.isin(['conflicts', 'repairs_filtered'])] # select all these columns

              conflicts  repairs_filtered
model_name
Auction             0.0               0.0
Ball                0.0               0.0
DSpace              0.0               0.0
JCGrid              0.0               0.0
SPEM                0.0               0.0
TIM                 2.0               2.0
TravelAgency       17.0               3.0
gcs                 2.0               1.0
glide               0.0               0.0
globus              0.0               0.0
oodt                0.0               0.0